### PR TITLE
update for latest Idris

### PR DESCRIPTION
**Pull request by clayrat**
Mostly fixes the syntax and adds necessary imports. I had to comment out some chunks due to:
* Interface resolution issues, hopefully these will be fixed by https://github.com/idris-lang/Idris-dev/pull/3936 in the next release
* half of `Data.Crypto.Encryption.DEA` depends on `bitsToFin` which is broken

### CODE REVIEW

**Comment by sellout** [comment]
Awesome, thanks. I’ll take a look at this today.

**Comment by clayrat** [comment]
Ok, I've fixed `bitsToFin` (wrong commit msg), but I'm still unable to uncomment the code in `Encryption.DEA` due to https://github.com/idris-lang/Idris-dev/issues/3971, and compiling `Bits`-using code without `--partial-eval` is not a good idea, as I've learned before.

**Comment by clayrat** [comment]
I tried building with the latest `master` version and the interface issues still persist, so I've opened a new issue: https://github.com/idris-lang/Idris-dev/issues/4072

**Comment by sellout** [comment]
If the PR I submitted against this PR looks good to you, I think this is good to merge.

**Pull request merged**
