### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by slaven-s**
Hi,

I added section "Books" and a link to the Type-Driven Development with Idris written by Edwin Brady for Manning Publications. We believe this book is a great resource and all members of community will benefit from this information. If you find this inappropriate, please let me know where I can publish it.

### CODE REVIEW

**Comment by david-christiansen** [comment]
It seems that this exact same pull request is being indiscriminately made to every Idris-related repo on Github. I consider this spam, and will close the ones on the idris-hackers organization and my own account.

**Comment by slaven-s** [comment]
Oh, I'm really sorry. :( 


     Datuma 22:33 Četvrtak, 10. Rujan 2015., David Christiansen <notifications@github.com> je napisao:
   

 It seems that this exact same pull request is being indiscriminately made to every Idris-related repo on Github. I consider this spam, and will close the ones on the idris-hackers organization and my own account. —

**Comment by david-christiansen** [comment]
Well, the deluge has at least ceased. In the future, a little note in one place would be nice before you send all those pull requests!

**Comment by slaven-s** [comment]
I'm really really sorry.I got to put Mr Brady's book on all possible places.
I am really really sorry.
 


     Datuma 23:03 Četvrtak, 10. Rujan 2015., David Christiansen <notifications@github.com> je napisao:
   

 Well, the deluge has at least ceased. In the future, a little note in one place would be nice before you send all those pull requests!—

**Comment by david-christiansen** [comment]
No worries, no damage done (other than 15 minutes of me chasing after and pasting a formulaic reply, plus some frustration :-]). I think it would have been more appropriate to post a single PR to the main repo, or perhaps to one of the idris-hackers repos, and in the text ask if it would be welcome to post the rest of them and then wait for an answer before going to every single one. Anyway, have a nice evening :)

**Comment by slaven-s** [comment]
Thank you very much. I didn't look on my e-mail while working. So PLEASE can I put it somewhere? If I can, please give me the link/links where I can put it. The book is really good and I would like to promote it as much as I can.
Again I'm really really sorry. I didn't look at my mail box.
 


     Datuma 23:08 Četvrtak, 10. Rujan 2015., David Christiansen <notifications@github.com> je napisao:
   

 No worries, no damage done (other than 15 minutes of me chasing after and pasting a formulaic reply, plus some frustration :-]). I think it would have been more appropriate to post a single PR to the main repo, or perhaps to one of the idris-hackers repos, and in the text ask if it would be welcome to post the rest of them and then wait for an answer before going to every single one. Anyway, have a nice evening :)—

**Comment by david-christiansen** [comment]
Edwin, the author, has the ability to put links in appropriate places. So do the maintainers of all these repositories. But I think it's best left up to each project maintainer to figure it out - each of us knows about the book and will do what we think makes the most sense.

**Comment by slaven-s** [comment]
Thank you once again.
 


     Datuma 23:15 Četvrtak, 10. Rujan 2015., David Christiansen <notifications@github.com> je napisao:
   

 Edwin, the author, has the ability to put links in appropriate places. So do the maintainers of all these repositories. But I think it's best left up to each project maintainer to figure it out - each of us knows about the book and will do what we think makes the most sense.—

**Comment by david-christiansen** [comment]
BTW, I just saw that you also put spam on each and every wiki. That was really not a nice thing to do - those take longer to set right than closing pull requests. Please don't do this again.

**Comment by slaven-s** [comment]
Is it possible to leave them without removing? PLEASE is the key word.:)
 


     Datuma 23:20 Četvrtak, 10. Rujan 2015., David Christiansen <notifications@github.com> je napisao:
   

 BTW, I just saw that you also put spam on each and every wiki. That was really not a nice thing to do - those take longer to set right than closing pull requests. Please don't do this again.—

**Comment by david-christiansen** [comment]
No, I'm not going to leave spam behind on wikis. That just encourages more.

**Pull request closed without merging**
